stages:
  - build
  - deploy

variables:
  MAIN_DOMAIN: "example.com"
  TARGET_ROOT: "google.com"
  REDIRECT_URL: "https://gov.cn"

build-docs:
  stage: build
  script:
    - echo "Building documentation..."
    - mkdir -p public/docs/{zh-CN,zh-TW,en-US,ru-RU}
    - cp -r docs/* public/docs/
  artifacts:
    paths:
      - public/

deploy-gitlab-pages:
  stage: deploy
  script:
    - echo "Deploying to GitLab Pages..."
  artifacts:
    paths:
      - public
  only:
    - main
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

deploy-cloudflare:
  stage: deploy
  script:
    - npm install -g @cloudflare/wrangler
    - wrangler deploy src/worker.js --name google-proxy --env production --vars "{\"MAIN_DOMAIN\":\"$MAIN_DOMAIN\"}"
  only:
    - main
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  environment:
    name: cloudflare
    url: https://$MAIN_DOMAIN

deploy-vercel:
  stage: deploy
  script:
    - npm install -g vercel
    - vercel --prod --token $VERCEL_TOKEN
  only:
    - main
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  environment:
    name: vercel
    url: https://$VERCEL_URL

deploy-netlify:
  stage: deploy
  script:
    - npm install -g netlify-cli
    - netlify deploy --prod --dir=dist --auth $NETLIFY_AUTH_TOKEN --site $NETLIFY_SITE_ID
  only:
    - main
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  environment:
    name: netlify
    url: https://$NETLIFY_URL