[build]
  command = "echo 'No build needed'"
  functions = "functions"
  publish = "docs"

[build.environment]
  MAIN_DOMAIN = "example.com"
  TARGET_ROOT = "google.com"
  REDIRECT_URL = "https://gov.cn"

[dev]
  command = "npm run dev"
  port = 8888

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/proxy"
  status = 200
  force = true