name = "google-proxy"
main = "src/worker.js"
compatibility_date = "2025-10-29"

[env.production]
account_id = "your_account_id"
workers_dev = false
route = "*.yourdomain.com/*"
zone_id = "your_zone_id"

[env.staging]
route = "staging.yourdomain.com/*"